### PR TITLE
Update tests, some fixes

### PR DESCRIPTION
**Pull request by Tieske**
Adds the following;

* moves main parser (`lxp`) tests to busted, adds some additional tests
* fixes makefile to also cleanup LuaRocks artifacts
* improves finishing, multiple calls no longer throw errors; ` parser:parse(); parser:parse()`
* moves `totable` parser tests to busted, adds some additional tests
* improves `totable` by having functions return the input table, allowing for easy chaining of calls
* documents `totable`

EDIT: added changes to `totable`

### CODE REVIEW

**Comment by tomasguisasola** [comment]
I am not used to these checks, but the code of src/lxp/totable.lua *is* using function pairs at line 57:

https://github.com/lunarmodules/luaexpat/blob/master/src/lxp/totable.lua#L57

I also run luacheck at my clone of the repository and it passed successfully.  Could you check what is going wrong here, please?

**Comment by Tieske** [comment]
That's because I removed the `pairs` there. What is the intended use in that code? Did you ever use it like this? or is it historical code?

imho it cannot ever work;
1. the way the iterator is used means that the 1st iterator result is used as input for the parser. With `pairs` that would be the `key`, not the `value`. So that would be weird.
2. `pairs` has an undetermined order, so impossible to validate the xml document chunks parsed if they are parsed in (potentially) random order.

Do you know how this has been used @tomasguisasola ? Are my changes correct? see https://github.com/lunarmodules/luaexpat/pull/11/files#diff-14a27057195b79f3f5a501efedc524d201852e80d173c9ba44c687965e211f53L57

**Comment by tomasguisasola** [comment]
I cannot remember why I made this code since I have never used it.  But I think it was an initial effort to include in LuaExpat an additional module to help manage XML verbosity.  At least in my experience, the XML objects are made as "records" or "arrays", not both, thus it would be handy to convert to tables using these particularities.

Anyway, I think it would be better to cut this file out until I organize it decently, including the docs.  What do you think?

**Comment by Tieske** [comment]
They were already in your branch, so I think we should keep them. I reworked the tests, that seems fine. And conceptually, dealing with records makes sense to me.

The code with the `pairs` iterator seems to have been copied from the `lom.lua` file which had the exact same problem. Since I'm convinced it couldn't ever have worked, I treated it as a bug, and fixed the code to treat the table as an array.

**Comment by Tieske** [comment]
I added documentation for `totable`, I'll merge this in the other PR, since by now it is creating quite some conflicts.

**Pull request merged**
