### PR TITLE
Use reusable workflow for luarocks deploy

### LINKED ISSUE #5: new release
@mwild1 what would be required for a new release?

What I've noticed;
- [ ] links in the documentation need updating
- [ ] this repo has [release 1.2.0 and 1.3.0 (tags)](https://github.com/lunarmodules/luaexpat/tags), yet [README.md](https://github.com/lunarmodules/luaexpat/blob/master/README.md) has 1.4.0... In the mailing list was mentioned [1.4.0 was to be released soon (tm)](http://lua-users.org/lists/lua-l/2022-01/msg00074.html)
- [ ] LuaRocks has [release 1.3.3 as latest](https://luarocks.org/modules/tomasguisasola/luaexpat)
- [ ] Ownership of LuaRocks is with @tomasguisasola currently. Should that stay?
- [ ] are there differences between @tomasguisasola released 1.3.3 and the current repo, that might break user expectations?

Any other concerns or things that need fixing/updating?

### PR DESCRIPTION
**Pull request by alerque**
Closes #5 (completes last undone of 11 steps)

This is dependent on:

- [x] Merging the [common workflow bits to the `.github` repo](https://github.com/lunarmodules/.github/pull/2) (which I don't have push access to yet).
- [x] After that merges I will test it from the sandbox repo again to make sure the syntax I'm proposing here is valid.
- [x] Then I'll take this out of draft mode.

In order to cut a release it will:

- [x] Also require the `LUAROCKS_APIKEY` secret per [this comment](https://github.com/lunarmodules/luaexpat/issues/5#issuecomment-1075060015).
- [ ] I suggest testing most of the workflow by touching the dev rockspec file in a commit on `master` and making sure that uploads properly.
- [ ] Finally a new tagged release can be published by creating a rockspec file in `rockspecs/` with the correct version filename and tagging the commit that touches said rockspec at the same time.

### CODE REVIEW

**Comment by alerque** [comment]
Note that there is one bit of the logic I'm not happy with. I coded it up based on how I thought it should work, but having done over a hundred tests in the sandbox repo I've decided it is a shortcomming: needing to both touch the rockspec file and add the tag at the same time is limited, especially in the case something goes wrong. I think this can be fixed from the reusable workflow bits, but I'll mess with it in a fork and the sandbox.

For now I think this can go ahead. Just be aware that to publish the 1.4.0 release one should twiddle *something* in the existing rockspec file (even if it is just adding a Lua comment) so that it shows up in the changed files list, and the tag the commit that touched the rockspec, then push the commit, then push the tag. Again that workflow should smooth out if I add the ability to test and upload rockspecs matching a tag if they exist before the tagged commit.

**Comment by Tieske** [comment]
not sure this logic is right. There are 2 tasks;
1. upload a release; rock+rockspec.
2. upload an SCM update; rockspec only
 
wrt releases: the rockspec belongs to the release, so one should always first commit the rockspec (to master/main), and then push the tags (otherwise the tag would not have the rockspec that belongs to it). So this should run whenever a NEW tag is found.

As for the SCM rockspec; it should be uploaded (using the `--force` option). Everytime it is changed, or one is added.

does that make sense?

**Comment by alerque** [comment]
Close.

We're good on the SCM rockspec. Whenever the file is messed with an attempt is made to rebuild it, and if the build works it force pushed is (with no pack, just the rockspec).

The issue is with release rockspecs. And what you said makes sense, and it will work that way. The issue is there is too tight a coupling between the commit that last touches the release-to-be's rockspec anad the commit that gets tagged as the release. Currently this requires they be the same commit.

What I would like to do is change that so that when a new tag is added it checks for an existing rockspec (even if it is HEAD~1 or HEAD~50) that matches the tag and if that builds, it tres to push it.

Currently only this sequence works:
```console
$ git add rockspecs/package-X.Y.Z-R.rockspec
$ git commit -m "Release X.Y.Z"
$ git tag X.Y.Z
```

What I am proposing as a future improvement is allowing intermediate commits such as
```console
$ git add rockspecs/package-X.Y.Z-R.rockspec
$ git commit -m "Add rockspec for upcomming release"
$ git add README.me
$ git commit -m "Update docs for next release"
$ git tag X.Y.Z
```

**Comment by alerque** [comment]
Just for the record I used almost this exact workflow (only the canonical repository name guard changed) to release Luacheck just recently. I had some issues with the Docker / GH Actions publishing part, but the LuaRocks deploy went off without a hitch.

**Comment by Tieske** [comment]
@alerque is this good to go? can we merge it, so we can tag and auto-release 1.4.0?

**Comment by alerque** [comment]
Yes this is ready to go as far as I can see.

Just remember the limitation about the tagged release commit *has to* touch the relevant rockspec. The release procedure should be to merge this PR, then add a release commit to the master branch. This commit can include as much or as little other updates as you need, but at a minimum it must change at least one bit in the 1.4.0 rockspec. Even adding a Lua comment is fine—it just has to show up in the diff stat for the commit to count. Then if the CI checks for that pass, add the tag (pushing from the CLI or adding the tag from the GitHub UI after the commit is pushed should both be fine).

**Comment by Tieske** [comment]
worked like a charm @alerque 🎉 🎉 🎉 🎉 

Both the 1.4.0 rockspec and the SCM rockspec are up now.

**Comment by Tieske** [comment]
That completes the new release. @mwild1 @tomasguisasola will either of you send out an email announcement on the Lua-List?

**Comment by mwild1** [comment]
I'll take care of that today. Thanks everyone!

**Comment by alerque** [comment]
I just took the liberty of using the GitHub interface to upgrade the tag from just a Git tag to a GitHub Release so that it shows up in the sidebar and under the [latest](https://github.com/lunarmodules/luaexpat/releases/latest) keyword. I copied the changelog notes from the #history section of the documentation index.

**Pull request merged**
