### PR TITLE
feat(threat) adds a compatible parser with threat protection

### PR DESCRIPTION
**Pull request by Tieske**
The parser is compatible with the normal expat parser. It will check for a variety of constraints and error out if it hits one;

```
		depth = 3,				-- depth of tags

		-- counts
		maxChildren = 3,		-- max number of children (DOM2;  Element, Text, Comment,
		                        -- ProcessingInstruction, CDATASection). NOTE: adjacent text/CDATA
								-- sections are counted as 1 (so text-cdata-text-cdata is 1 child).
		maxAttributes = 3,		-- max number of attributes (including default ones), if not parsing
								-- namespaces, then the namespaces will be counted as attributes.
		maxNamespaces = 3,		-- max number of namespaces defined on a tag

		-- sizes
		document = 200,			-- size of entire document in bytes
		buffer = 100,			-- size of the unparsed buffer in bytes
		comment = 20,			-- size of comment in bytes
		localName = 20,			-- size of localname (or full name if not parsing namespaces) in bytes,
								-- applies to tags and attributes
		prefix = 20,			-- size of prefix in bytes (only if parsing namespaces), applies to
								-- tags and attributes
		namespaceUri = 20,		-- size of namespace uri in bytes (only if parsing namespaces)
		attribute = 20,			-- size of attribute value in bytes
		text = 20,				-- text inside tags (adjacent text/CDATA)
		PITarget = 20,			-- size of processing instruction target in bytes
		PIData = 20,			-- size of processing instruction data in bytes
		entityName = 20,		-- size of entity name in EntityDecl in bytes
		entity = 20,			-- size of entity value in EntityDecl in bytes
		entityProperty = 20,	-- size of systemId, publicId, or notationName in EntityDecl in bytes
```

Inspired by;

- https://docs.sensedia.com/en/api-platform-guide/4.2.x.x/interceptors/security_xml-threat-protection.html
- https://tech.forums.softwareag.com/t/xml-threat-protection/236959
- https://docs.mulesoft.com/api-manager/2.x/apply-configure-xml-threat-task
- https://github.com/Trust1Team/kong-plugin-xml-threat-protection

### CODE REVIEW

**Comment by Tieske** [comment]
@mwild1 Any thoughts on this?

**Comment by mwild1** [comment]
If it's:

- [x] optional
- [x] tested
- [ ] documented
- [x] doesn't bloat the library (~9KB)

it seems fine to me. I don't personally have a use-case for it, as I think limiting after parsing has less value than limiting before parsing. After parsing I'm not sure exactly what the attack vectors are.

I also didn't spot any tests where the problematic elements are split over multiple `:parse()` calls. I don't think it makes any difference for this code, but it's probably a case worth testing for.

**Comment by Tieske** [comment]
> I also didn't spot any tests where the problematic elements are split over multiple `:parse()` calls. I don't think it makes any difference for this code, but it's probably a case worth testing for.

These: https://github.com/lunarmodules/luaexpat/pull/3/files#diff-86a7914fbb76f29cacca5d77f9553eee05de506bfdb11a0a2c6d0af0ad0bd4b5R378-R454

**Comment by Tieske** [comment]
> it seems fine to me. I don't personally have a use-case for it, as I think limiting after parsing has less value than limiting before parsing. After parsing I'm not sure exactly what the attack vectors are.

So far what I've seen folks do is use libxml2, parse the full doc, traverse it and throw an error if it doesn't stay within the limits set. There is limited value in that, hence I wanted to create it on top of expat, since it streams. 

While it streams it will [record the validation error, stop the parser](https://github.com/lunarmodules/luaexpat/pull/3/files#diff-73513add1a84ef87822f4c89e6f0fdc14de13d59621bb0613f7e39d1ccc69841R29-R34) and when the `parse` call returns it will [replace the results with the validation error](https://github.com/lunarmodules/luaexpat/pull/3/files#diff-73513add1a84ef87822f4c89e6f0fdc14de13d59621bb0613f7e39d1ccc69841R52-R57).

So while not perfect, it will stream & validate, it does not depend on first parsing the entire document. So I think it addresses your comment...

**Comment by mwild1** [comment]
> So while not perfect, it will stream & validate, it does not depend on first parsing the entire document. So I think it addresses your comment...

Yeah, not the whole document I understand. Doing it after that is pointless :)

But some of the limits, such as the size of an attribute value, can only be caught after the string has been parsed and imported into Lua, right? So if I do: `<data foo='[...2GB of data...]'/>` it would blow up the RAM before rejecting the value. I guess I'm just not really sure what "threat" these limits are supposed to be protecting against.

**Comment by Tieske** [comment]
Correct. Hence the generic `document` size to maximize the docs itself. And despite not being able to address the whole thing, memory pressure for validating "good" docs will be reduced drastically, whereas with crafted "bad" docs it will still go up. (use-case is a proxy, where the document is not actually consumed on the proxy itself, just validated before being send upstream)

**Comment by Tieske** [comment]
> But some of the limits, such as the size of an attribute value, can only be caught after the string has been parsed and imported into Lua, right?

just added a new commit that introduces "unparsed buffer" checks. That should deal with the issue.

**Comment by Tieske** [comment]
converted to draft since it needs the new handlers from #17

**Review by tomasguisasola — APPROVED** [review]

**Pull request merged**
